# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.Api/Dockerfile
    ports:
      - 5197:5197
